export const methods = [
    { id: 0, name: "Jafari / Shia Ithna- Ashari"
    },
    { id: 1, name: "University of Islamic Sciences, Karachi"
    },
    { id: 2, name: "Islamic Society of North America"
    },
    { id: 3, name: "Muslim World League"
    },
    { id: 4, name: "Umm Al-Qura University, Makkah"
    },
    { id: 5, name: "Egyptian General Authority of Survey"
    },
    { id: 7, name: "Geofizika İnstitutu,Tehran Universiteti"
    },
    { id: 8, name: "Gulf Region"
    },
    { id: 9, name: "Kuwait"
    },
    { id: 12, name: "Union Organization islamic de France"
    },
    { id: 13, name: "Diyanet İşleri Başkanlığı, Türkiyə"
    },
    { id: 14, name: "Rusiya müsəlmanları idarəsi"
    },
    {
    id: 23,
    name: "Vəqf Nazirliyi,İslami işlər,İordaniya",
    },
];

export const countrynames = {
  Azerbaijan: "Azərbaycan",
  Turkey: "Türkiyə",
    // US: "ABŞ",
    // Russia: "Rusiya",
    // Iran: "İran",
    // Georgia: "Gürcüstan",
};

export const citynames = {
  Azerbaijan: [
        {
      Aghdam: "Ağdam",
      Agdash: "Ağdaş",
      Aghjabadi: "Ağcəbədi",
      Agstafa: "Ağstafa",
      Agsu: "Ağsu",
      Astara: "Astara",
      Aghdara: "Ağdərə",
      Babek: "Babək",
      Baku: "Bakı",
      Balakan: "Balakən",
      Barda: "Bərdə",
      Beylagan: "Beyləqan",
      Bilasuvar: "Biləsuvar",
      Dashkasan: "Daşkəsən",
      Fuzuli: "Füzuli",
      Gadabay: "Gədəbəy",
      Ganja: "Gəncə",
      Goranboy: "Goranboy",
      Goychay: "Göyçay",
      Goygol: "Göygöl",
      Hajigabul: "Hacıqabul",
      Imishli: "İmishli",
      Ismayilli: "İsmayıllı",
      Jabrayil: "Cəbrayıl",
      Julfa: "Culfa",
      Kalbajar: "Kəlbəcər",
      Khachmaz: "Xaçmaz",
      Khankendi: "Xankəndi",
      Khojavend: "Xocavənd",
      Khirdalan: "Xirdalan",
      Kurdamir: "Kürdəmir",
      Lankaran: "Lənkəran",
      Lerik: "Lerik",
      Masalli: "Masallı",
      Mingachevir: "Mingəçevir",
      Nakhchivan: "Naxçıvan",
      Naftalan: "Naftalan",
      Neftchala: "Neftçala",
      Oghuz: "Oğuz",
      Ordubad: "Ordubad",
      Qabala: "Qəbələ",
      Qakh: "Qax",
      Qazakh: "Qazax",
      Quba: "Quba",
      Qubadli: "Qubadlı",
      Qusar: "Qusar",
      Saatly: "Saatlı",
      Sabirabad: "Sabirabad",
      Shabran: "Şabran",
      Shahbuz: "Şahbuz",
      Shaki: "Şəki",
      Shamakhi: "Şamaxı",
      Shamkir: "Şəmkir",
      Sharur: "Şərur",
      Shirvan: "Şirvan",
      Siyazan: "Siyəzən",
      Shusha: "Şuşa",
      Sumqait: "Sumqayıt",
      Tartar: "Tərtər",
      Tovuz: "Tovuz",
      Ujar: "Ucar",
      Yardimli: "Yardımlı",
      Yevlakh: "Yevlax",
      Zaqatala: "Zaqatala",
      Zardab: "Zərdab",
      Zangilan: "Zəngilan",
      Kangarli: "Kəngərli",
      Sadarak: "Sədərək",
        },
    ],
  Turkey: [
        {
      Adana: "Adana",
      Adıyaman: "Adıyaman",
      Afyonkarahisar: "Afyonkarahisar",
      Ağrı: "Ağrı",
      Amasya: "Amasya",
      Ankara: "Ankara",
      Antalya: "Antalya",
      Artvin: "Artvin",
      Aydın: "Aydın",
      Balıkesir: "Balıkesir",
      Bilecik: "Bilecik",
      Bingöl: "Bingöl",
      Bitlis: "Bitlis",
      Bolu: "Bolu",
      Burdur: "Burdur",
      Bursa: "Bursa",
      Çanakkale: "Çanakkale",
      Çankırı: "Çankırı",
      Çorum: "Çorum",
      Denizli: "Denizli",
      Diyarbakır: "Diyarbakır",
      Edirne: "Edirne",
      Elazığ: "Elazığ",
      Erzincan: "Erzincan",
      Erzurum: "Erzurum",
      Eskişehir: "Eskişehir",
      Gaziantep: "Gaziantep",
      Giresun: "Giresun",
      Gümüşhane: "Gümüşhane",
      Hakkâri: "Hakkâri",
      Hatay: "Hatay",
      Isparta: "Isparta",
      Mersin: "Mersin",
      İstanbul: "İstanbul",
      İzmir: "İzmir",
      Kars: "Kars",
      Kastamonu: "Kastamonu",
      Kayseri: "Kayseri",
      Kırklareli: "Kırklareli",
      Kırşehir: "Kırşehir",
      Kocaeli: "Kocaeli",
      Konya: "Konya",
      Kütahya: "Kütahya",
      Malatya: "Malatya",
      Manisa: "Manisa",
      Kahramanmaraş: "Kahramanmaraş",
      Mardin: "Mardin",
      Muğla: "Muğla",
      Muş: "Muş",
      Nevşehir: "Nevşehir",
      Niğde: "Niğde",
      Ordu: "Ordu",
      Rize: "Rize",
      Sakarya: "Sakarya",
      Samsun: "Samsun",
      Siirt: "Siirt",
      Sinop: "Sinop",
      Sivas: "Sivas",
      Tekirdağ: "Tekirdağ",
      Tokat: "Tokat",
      Trabzon: "Trabzon",
      Tunceli: "Tunceli",
      Şanlıurfa: "Şanlıurfa",
      Uşak: "Uşak",
      Van: "Van",
      Yozgat: "Yozgat",
      Zonguldak: "Zonguldak",
      Aksaray: "Aksaray",
      Bayburt: "Bayburt",
      Karaman: "Karaman",
      Kırıkkale: "Kırıkkale",
      Batman: "Batman",
      Şırnak: "Şırnak",
      Bartın: "Bartın",
      Ardahan: "Ardahan",
      Iğdır: "Iğdır",
      Yalova: "Yalova",
      Karabük: "Karabük",
      Kilis: "Kilis",
      Osmaniye: "Osmaniye",
      Düzce: "Düzce",
        },
    ],
};
